# Generated by Django 2.1.3 on 2018-11-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feature',
            new_name='featured',
        ),
    ]
